# Generated by Django 3.0.5 on 2021-05-29 17:12

import blogs.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=blogs.models.Blog)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
